### ISSUE TITLE
Trends in ADU Permits 

### ISSUE THREAD

**Issue by unstasis** [hackoregon/2019-housing-data-science#6]
# Story Card Request

**Project: HOUSING**    
**Card Title:**        
**Card Document:** (https://docs.google.com/document/d/1tBi_VvcVelG0lprx7hqFHmDjSalcf09K6AugvfbPtzM/edit)        

## Milestones
Context
(We hypothesize that) there are certain areas within the Portland MSA that have greater concentrations of permits drawn.  (We hypothesize that) these areas have certain similarities that illustrate common claims about equity in ADU development.   

The 2013 Oregon DEQ survey of ADU owners points to financing as the greatest obstacle in ADU construction, with the majority of respondents having paid in cash or with a home equity line of credit.   While the greater number of small square-footage units in the city does create more affordable options, those property owners who already have considerable capital (are hypothesized to) disproportionately benefit from the long-term gains resulting from the development.  There are a number of programs to close this gap under way, including new models of bank financing programs, nonprofit groups educating about DIY possibilities and grant-funding, and scholarly work demonstrating the added value to the property of ADUs to enable more traditional loans.
Key metrics:
Unit:  Census Tract
Examining:  Concentration of ADU permits (completed ADU permits?)
Median Income, or
Median Rent/Home Price

### Setup
- [ ] Create Card Document from [this template](https://docs.google.com/document/d/1tBi_VvcVelG0lprx7hqFHmDjSalcf09K6AugvfbPtzM/edit) and link above     

### Type of data processing / analysis this story card uses 
Each card can belong to one or more categories listed below

- [x] descriptive - simple data (re)-representation, doing summary statistics belongs to this category, we do this for all data sets      
- [ ] explanatory - testing hypotheses and / or comparing data points     
- [ ] predictive - any regression, model fitting, classification or clustering tasks      
- [ ] prescriptive - when you want to recommend any action to be taken (we do this rarely, if at all)     

### Data documentation and proposed analysis
- [ ] Document [metadata](https://forms.gle/7aL8U3Y9ANNz9oda7)       
- [ ] Decide whether to load to database or S3 with proper metadata documentation       
- [ ] Review metadata and proposed data analysis      

1. Version control all the scripts used to process the data by cloning 2019HackORDataScienceTemplate repository, then change the name to follow the convention 
E.g. 2019-{TEAM-NAME}-data-science, or 2019-housing-data-science

2. Prototyping and testing analysis proposals
You are encouraged to provide a prototype of your analysis using Jupyter notebook or Rmarkdown notebooks and then store the prototyping notebooks under 

2019-{TEAM-NAME}-data-science/notebooks/

3. once you finalize the analysis for a story card, you are encouraged to extract reusable functions into a python scripts and for each story card 

2019-{TEAM-NAME}-data-science/src/data/make_dataset.py
2019-{TEAM-NAME}-data-science/src/features/build_features.py

6. We recommend having a jupyter notebook / bash script or python script that can run the data-pipeline for producing each story card / workflow from end-to-end to its final form. Example below:
#!/bin/bash 
TEAM-NAME=housing
cd 2019-{TEAM-NAME}-data-science

# pull data appropriately
# minimal transformation is done at this stage but you 
# can save the downloaded data as a file to the “interim” folder on S3 # or interim data table on RDS
python ./src/data/make_dataset_story_card_1.py

# transform, filter, do ETL (extract transform load task)
# the dataset write out to a file / RDS would live as the “processed” # folder
python ./src/features/build_features_story_card_1.py

# provide prototype visualization of the dataset if applicable
python ./src/visualization/visualize_story_card_1.py

7.. There should also be a Dockerfile documenting the library dependencies as 2019-{TEAM-NAME}-data-science/build/Dockerfile
And / or accompanying docker-compose.yml file at 
2019-{TEAM-NAME}-data-science/build/docker-compose.yml
For more detailed guidelines for the best practices to follow when documenting a story card / data workflow. Please refer to the data science best practices documentation

### Set up data processing development environment   
- [ ] Clone repo from [template] (https://github.com/karenng-civicsoftware/HackORDataScienceTemplate)       

We hypothesize that) there are certain areas within the Portland MSA that have greater concentrations of permits drawn.  (We hypothesize that) these areas have certain similarities that illustrate common claims about equity in ADU development.   
- [ ] Set up access to GitHub repo for all team members
- [ ] Set up a container from a suitable version of the [Dockerfile template](https://github.com/karenng-civicsoftware/HackORDataScienceTemplate/blob/master/build/Dockerfile)       
- [ ] Prototyping and testing analysis proposals       
- [ ] Review additional proposed data analysis identified through prototyping       
- [ ] Write code for reproducible data processing steps with proper version control & data lineage    
- [ ] Data science results produced and documented      
- [ ] Data science peer reviewed        

### Build APIs
- [ ] Database deployed to CIVIC Cloud      
- [ ] Data science results available through API with all needed calculations, filters and queries       
- [ ] Basic API in container       
- [ ] Basic API deployed to CIVIC Cloud       
- [ ] TBD process for API design - standardization?        
- [ ] API endpoint with all needed calculations, filters and queries        

### Data visualization:
- [ ] Clear concept        
- [ ] All components needed available in [Storybook](https://hackoregon.github.io/civic/)       
- [ ] Components available in [Storybook](https://hackoregon.github.io/civic/) demonstrate all needed features      
- [ ] Follows data visualization and interface guidelines available in [Storybook](https://hackoregon.github.io/civic/)        

### Design
- [ ] TBD Wireframes?     
- [ ] TBD Design review?     

### Written content / additional links
- [ ] Write content     
- [ ] Review content
